version: '3.5'

services:
  example-pyapi:
   image: example-pyapi
   container_name: example-pyapi
   ports: 
     - "15000:5000"
   build:
     context: .
     dockerfile: ApiEndpoint/Dockerfile
   networks:
     - example-ntw
     

  example-svc: 
    image: ${DOCKER_REGISTRY-}example-svc
    container_name: example-svc
    ports:
      - "15008:15008"
    build: 
      context: .
      dockerfile: ExampleService/Svc.Implementation/Dockerfile
    entrypoint: ["dotnet", "Svc.Implementation.dll"]
    networks:
      - example-ntw
     

networks:
  example-ntw:
    name: example-ntw
    driver: bridge     